### ISSUE TITLE
[FEATURE] Allow taking WADM_NATS_JWT from the CLI

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#100]
Previously, you could specify a NATS JWT and seed in order to authenticate with a NATS server over the command line entirely, not needing files. In wadm v0.4.0-alpha.1, the JWT is a pathbuf, so you will have to provide a file path in order to use this authentication method, in which case you could just use a credsfile. 

I would like to be able to supply a JWT and seed on the CLI to keep this simple, e.g.
```
WADM_NATS_JWT=eyJWTthings WADM_NATS_NKEY=SUASDASDASD wadm
```

**Comment by stephenandary** [comment]
Is this possible on the chart?

**Comment by stephenandary** [comment]
Is it possible to use Env Variables for values in link def on charts?
