### ISSUE TITLE
[DOCUMENTATION] Create Design Pattern Diagrams for WADM Documentation

### ISSUE THREAD

**Issue by stephenandary** [wasmCloud/wadm#105]
Would be wonderful to include or update diagrams found here: https://github.com/wasmCloud/wadm/issues/15 such that it reflects the new design patterns within WADM.

**Comment by stephenandary** [comment]
WIP

Building a map for myself prior to comments so it is easier to create a diagram. All of this is already documented withing directories. Just trying to have it in 1 place as a table of contents for diagram development. 

Will be updating this as I progress. This comment will be edited. Will make it complete when done. 

## Directories

root/

- bin/
  - connections.rs:
    - A module for connection pools and generators. This is needed because control interface clients (and possibly other things like nats connections in the future) are lattice scoped or need different credentials
  - logging.rs:
    - otel tracing code
  - main.rs:
    - application
  - nats.rs:
    - client and helper code
  - observers.rs:
    - Types for observing a nats cluster for new lattices

- src
  - lib.rs:
    - library root to make underlying crates in src available for bin. Default topics and metadata.
  - nats_utils.rs
    - helper utilities for working with nats
  - publisher.rs
    - generic nats publisher traits for testing and flexibility
  - test_util.rs
    - test utilities

  - commands/
    - mod.rs:
      - Type implementations for commands issued to compensate for state changes

  - consumers/
    - mod.rs:
      - Contains implementions of durable consumers of events that automatically take a message from a consumer and parse it to concrete types for consumption in a scheduler
    - commands.rs:
      - A module for creating and consuming a stream of commands from NATS
    - events.rs:
      - A module for creating and consuming a stream of events from a wasmcloud lattice
    - manager.rs:
      - Contains manager and worker code. A manager of a specific type of Consumer that handles giving out permits to work and managing per lattice consumers. A worker is any type that can perform work based on a given [`ScopedMessage`]. This worker should contain all state (or handles to state) that it needs to complete its work

  - events/
    - mod.rs:
      - exposing modules
    - data.rs:
      - types related to claims,linkdefs, actor and provider identity.
    - deser.rs:
      - Custom deserializers for event fields
    - ser.rs:
      - Custom serializers for event fields
    - types.rs:
      - Common event types expected on wasmbus. These are the inner types generally sent in the `data` attribute of a cloudevent

  - mirror/
    - mod.rs:
      - This is a temporary workaround to let us combine multiple topics into a single stream so consumers work using it in wasmcloud projects

  - model/
    - mod.rs:
      - Types and implementations for OAM manifest fields
    - internal.rs
      - Contains the internal storage definition of a manifest

  - scaler/
    - mod.rs  
    - manager.rs
    - simplescaler.rs
    - spreadscaler/
      - mod.rs
      - link.rs
      - providers.rs

  - server/
    - mod.rs
    - handlers.rs
    - notifier.rs
    - parser.rs
    - types.rs

  - storage/
    - mod.rs
    - nats_kv.rs
    - reaper.rs
    - state.rs

  - workers/
    - mod.rs
    - command.rs
    - event_helpers.rs
    - event.rs

**Comment by stephenandary** [comment]
@thomastaylor312 What is the purpose of having a simplescaler and a spreadscaler that also has an actor spread scaler? Do they do different things?

**Comment by brooksmtownsend** [comment]
@stephenandary not Taylor, but just wanted to let you know the simplescaler was developed just to prove out the `Scaler` trait and to validate some initial tests. It's definitely more of a test implementation than a fully featured scaler 😄

**Comment by stephenandary** [comment]
Ok cool, thanks @brooksmtownsend. Just trying to get to good mental map for diagram. 1 thing I don't need to worry about now woot woot haha

**Comment by stephenandary** [comment]
@brooksmtownsend or @thomastaylor312 , can I please make sure I am covering all of the components of wadm that may be relevant to a diagram: 

Components: 
- Server
- Nats KV
- Nats Event Stream
- SpreadScaler
- Command Manager
- Event Manager
- Command Worker
- Event Worker

Does this make sense? Am I missing anything or is something incorrect?

**Comment by stephenandary** [comment]
I also see there are multiple streams, but I don't know if that should be on a diagram as a mirror is just modifying stream to be usable due to nats limitations in current version. 

I also see an observer in Bin, should that be a component?

**Comment by stephenandary** [comment]
Also, what is emitting events to the event stream?

**Comment by stephenandary** [comment]
Per Taylor: Only events are from wasmbus.rpc and from wadm itself

**Comment by stephenandary** [comment]
I am also noticing a lot of similarities between wadm and concordance with language. Is this language internal, or is there some design model that it is based on? Some form of event-driven architecture maybe?

**Comment by brooksmtownsend** [comment]
@stephenandary that last one might just be us formalizing on some terminology, but they aren't related per se. If there's a specific example we could elaborate though!

**Comment by stephenandary** [comment]
ConsumerManagers is 1 example

**Comment by stephenandary** [comment]
Let me know what you want me to do with this issue (keep open or close), moving onto some other work now and no longer have time.

**Comment by brooksmtownsend** [comment]
@stephenandary I like this layout of the repo both in filenames and in concepts. I think what we should do is, once we get some time together, pop into a diagram tool while we're all on a call so we can sketch out the architecture. That will be fun!

**Comment by stephenandary** [comment]
Hey @brooksmtownsend, I have moved onto other work now so I don't have any time in near future. Hopefully someone else can help with this. Otherwise if you need me to close this issue let me know.

**Comment by brooksmtownsend** [comment]
No worries @stephenandary! It's not urgent, just wanted to update the status. I like the issue

**Comment by stephenandary** [comment]
Closing issue to remove from my issue log.
