### ISSUE TITLE
Provider scaler should only check if a provider exists when matching scale requirements

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wadm#106]
There are going to be many times where a capability provider is "shared" between different applications (think something like the httpserver provider). Right now if one is already running, then every single reconcile will trigger a command that fails if some other application is running the provider.

To solve this I think the solution should be that the provider scaler should _NOT_ match on annotations and only check if a provider with the correct linkname is running on hosts that match its spread requirements. It should also run a reconcile _anytime_ it sees a provider stopped event. This is correct behavior because all that this is checking for is that a host _has_ that capability, it doesn't matter what is running it. If for some reason that provider is deleted (by a user or by another application that has been deleted), then the scaler should make sure it is running again for the application

Please note that this isn't perfect. In the future I'd like to avoid the, albeit short, downtime of a provider stopping and then starting again, but that will require some sort of shared state between all of the different scalers

**Comment by stephenandary** [comment]
I can grab this if time is not a constraint

**Comment by thomastaylor312** [comment]
Sure thing! Just let us know if you start working on it and I'll mark it as reserved

**Comment by stephenandary** [comment]
Starting on Monday, I feel Monday is a clean start.

**Comment by stephenandary** [comment]
No longer going to be able to get to this one. Will be moving on to some other work and no longer have time.

**Comment by brooksmtownsend** [comment]
Reopening this one as it seems to still be an issue, but possibly only for newly created scalers. I've noticed that if I create an app that deploys a provider, say HTTPserver with link `default`, and then another app with the same provider, it can occasionally not recognize the other provider and continually try to start HTTPserver again. More investigation needed.

**Comment by brooksmtownsend** [comment]
Closed by #167
