### ISSUE TITLE
Add a client library

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wadm#107]
Right now we basically consume the raw NATS API everywhere we interact with wadm. It would be nice if we added a client library to the wadm crate so that we could have an experience like `client.put_manifest(Manifest{}).await`. This could become more helpful down the line too as we add more features

**Comment by brooksmtownsend** [comment]
This would probs be really similar to the way that https://github.com/wasmCloud/wash/blob/main/crates/wash-lib/src/app.rs is structure
