### ISSUE TITLE
Validate manifests before accepting them

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wadm#122]
Right now we blindly accept manifests without any validation. This causes issues where you might have misplaced something like your spread definitions and also leads to manifests fighting with each other (if two different manifests link to the same provider with different values, so those scalers each try to compete to set their version of the linkdef). At the minimum, validation should probably include:

- Collision with other manifests, particularly with actor/provider versions, and linkdefs with different values for the same actor
- Unrecognized or missing fields when parsing the manifest

**Comment by thomastaylor312** [comment]
One possible solution here is to define a json schema and use that: https://docs.rs/jsonschema/latest/jsonschema/

**Comment by brooksmtownsend** [comment]
Consider #123 and @autodidaddict's scenarios when validating the manifests

**Comment by brooksmtownsend** [comment]
One more comment, I think this issue should cover the problem outlined in https://github.com/wasmCloud/wadm/issues/131 and reject non-string label requirements.

**Comment by aish-where-ya** [comment]
Here are some of the cases covered in #153 

- Multiple actors or providers cannot have the same names in a single manifest
- A linkedef - provider reference pair needs to be unique in a capability provider definition.
- Linkdefs in a manifest should have a unique target

The next PR will cover validation using a JSONSchema for manifest items.
