### ISSUE TITLE
[RFC] The state of the state(s)

### ISSUE THREAD

**Issue by janitha09** [wasmCloud/wadm#15]
https://mermaid.live 
https://mermaid-js.github.io/mermaid/#/entityRelationshipDiagram
Looking through the code that has been written up this is my mental picture
```mermaid
erDiagram
          WASMCLOUD_HOST ||--|| State : has
          State }|..o{ Actor : has
          State }|..o{ Provider : has
          State }|..o{ Link_Definiton : has
          LATTICE_OBSERVER }|--|| Lattice : has
          Lattice ||--|| State: contains
          WADM ||--o| Deployment_State : has
          Deployment_State }|..o{ Actor : has
          Deployment_State }|..o{ Provider : has
          Deployment_State }|..o{ Link_Definiton : has
```

![image](https://user-images.githubusercontent.com/13897587/148154889-f89ef483-8a6a-4ee8-8534-824decd6272b.png)

```mermaid
graph TD
    A[Updated OAM Spec] -->|Apply| B(HOST_CORE)
    B -->|Spin Up| C(Actor/Provider/Link)
    C --> |Reconcile| D{Diff}
    D -->|Yes/Apply/Backoff| B
    D -->|No| E[Done]
    F[WASHBOARD]-->|manual entry| B
```
![image](https://user-images.githubusercontent.com/13897587/148154798-f552dcb9-cdc1-4859-b201-d3bd1c09c133.png)

How is the contention between the UI and OAM spec going to be handled - who wins? Last in?

Incomplete thoughts  - Since Horde is involved WADM is a singleton? Haven't processed that. Redis will maintain....

**Comment by janitha09** [comment]
@autodidaddict

**Comment by brooksmtownsend** [comment]
Closing since we can continue discussion in #105 as we move forward with the Rust architecture
