### ISSUE TITLE
[FEAT] Support upgrades of just link config or provider config

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#159]
Currently, the check to ensure that a scaler is meaningfully different from a previous version is done by comparing the IDs to each other. However, the ID for a link scaler does not include its values, and the ID for a provider scaler does not include its provider config. We should generate some form of short hash of linkdef values and provider and append that to the ID so we can delete + put a link, or stop + start a provider when the configuration changes.

**Comment by ahmedtadde** [comment]
hey @brooksmtownsend , i created a draft PR that has changes to address this issue for the `SpreadScaler > LinkScaler`. It is a p.o.c and i want to get some feedback to know if this is in alignment with what you have in mind. If yes, I can go ahead and do the same for the `SpreadScaler > ProviderScaler` (and which other ones?). If not, a pointer or two to set me on the right path would be great.

**Comment by brooksmtownsend** [comment]
@ahmedtadde left some feedback, I think it's exactly what I had in mind! I think the same should be done for the provider SpreadScaler and the provider DaemonScaler since they are both in charge of starting providers. Your approach with `values` should effectively be the same as `config` there to get the hash.

Once you get that updated I think we should look into adding some extra cases to the e2e upgrade test where we test _only_ modifying a link value and a provider config and assert that worked. If you run into any test flakes let me know, we've been trying to improve them lately. As far as I could see with my testing, e2e_multitenant sometimes fails on a status assertion but the core logic works.

**Comment by ahmedtadde** [comment]
hey @brooksmtownsend i pushed several commits for the provider config hash (both, `spreadscaler & daemonscaler`). I also updated `e2e_upgrade` ( let me know if the added test code actually does enough to be useful with regards to the code changes).

**Comment by connorsmith256** [comment]
@brooksmtownsend should this be closed?
