### ISSUE TITLE
Refactor manifest upgrade for more efficient scaler computation

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#161]
In the event worker, this section of code is a little inefficient: https://github.com/wasmCloud/wadm/blob/main/src/workers/event.rs#L704-L734

This ends up computing scalers twice for an individual manifest, first to compute the difference between the old and the new manifests and then again in order to actually add the scalers to the ScalerManager. Instead of the rigid `add_scalers` function, it would be great to be able to compute scalers separately and then directly add scalers from a slice of scalers, instead of having to pass in an unprocessed manifest each time.

**Comment by thomastaylor312** [comment]
Closed in #183
