### ISSUE TITLE
[FEAT]: Graph representation for entities in a wadm manifest

### ISSUE THREAD

**Issue by aish-where-ya** [wasmCloud/wadm#168]
Currently, to iterate through a WADM manifest spec, we loop through the components such as Actors and Providers and their associated Traits (Linkdefs, Spreadscalers or Custom Traits). Since we spin up the entities in a lattice using a manifest, it would be a nice idea to represent the lattice as a graph and the entities as nodes or connections in the graph. 

This would make the system efficient to use because we won't have to iterate through the manifest using loops every time we need to find out the relationships between entities. Once represented as a graph, it would be easier to use graph traversal to retrieve the entities, their relations as well as their details efficiently.

**Comment by thomastaylor312** [comment]
Love this idea!
