### ISSUE TITLE
[FEAT] Add the ability to set a stream prefix for all wadm internal streams

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wadm#180]
When running in a multitenant environment, clients will need to share the same JS domain (since messages need to come from lattices). However, this means you can't have a separate stream for different wadm's running in a multitenant environment (e.g. `wadm_status`).

I think it would be good to allow a user to configure a stream prefix that would be added to each stream: `<myprefix>_wadm_status`

**Comment by ahmedtadde** [comment]
Hello @thomastaylor312 , Assuming this still available to be worked on (and still relevant), i'd like to take a stab at it. so far, i have not been able to pin point the place(s) in the code to make this change. I looked at `nats_utils`, `lib` (ie, the constant prefixes in there), `workers/*`, `consumers/*` and `events/*` and I could readily determine where the change will need to be made. I'd appreciate a push in the right direction; maybe there is some context that I am missing.

**Comment by thomastaylor312** [comment]
Sorry for the delay @ahmedtadde. So this is actually in the `bin/` directory. We have a bunch of `const`s we have there right now: https://github.com/wasmCloud/wadm/blob/867793f871f80d038ba7070abc1281ae4748b034/bin/main.rs#L3. So you'd add a new flag that would allow you to set a prefix and use it in conjunction with those constants

**Comment by brooksmtownsend** [comment]
closed by #188
