### ISSUE TITLE
Make status stream less noisy

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wadm#187]
Right now, scalers will update the status stream consistently with a "ready" status even when nothing has changed. This can make the stream a bit noisy and push out useful data from previous statuses. We should update the logic to only push status changes when ready if the status changes from ready

**Comment by thomastaylor312** [comment]
@brooksmtownsend since you wrote the status code, do you think this could be labeled good first issue?

**Comment by brooksmtownsend** [comment]
I think this could be a good issue, I think the hard part would just be getting the status information down to the scaler manager that's publishing out the status, but that's mostly just reorganizing 🤔

**Comment by thomastaylor312** [comment]
Thinking about this some more, I think we should try to dedup _all_ messages. This could possibly be done with NATS configuration or by checking the last message
