### ISSUE TITLE
[FEATURE] Return more fine-grained errors from WADM handlers

### ISSUE THREAD

**Issue by joonas** [wasmCloud/wadm#225]
**Is your feature request related to a problem? Please describe.**

Currently handlers respond with a single type of [error (`"result": "error"`)](https://github.com/wasmCloud/wadm/blob/main/src/server/handlers.rs#L894-L907), which makes it tedious to handle errors on the client-side when calling in.

**Describe the solution you'd like**

It would be fantastic, if each of the wadm handlers had a set of errors that represented the different scenarios that might go wrong or validations on wadm's side which it could then return to the caller. This would make it easier to handle error results from wadm in a more graceful and intelligent fashion.

**Describe alternatives you've considered**

None.

**Additional context**

None.

**Comment by joonas** [comment]
This isn't stable 🙂

**Comment by brooksmtownsend** [comment]
@joonas Do you think this is resolved with the `wadm-client` crate and the inclusion of a `ClientError`? Or is there more detail you'd like to have here https://docs.rs/wadm-client/0.3.0/wadm_client/error/enum.ClientError.html

**Comment by joonas** [comment]
> @joonas Do you think this is resolved with the `wadm-client` crate and the inclusion of a `ClientError`? Or is there more detail you'd like to have here https://docs.rs/wadm-client/0.3.0/wadm_client/error/enum.ClientError.html

Yep, I think that's a great starting point that we can expand upon as new cases crop up, going to close this out.
