### ISSUE TITLE
[FEATURE] Improve wadm manifest validation

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wadm#244]
From @brooksmtownsend:
> wadm manifest validation should not accept spread blocks being empty or at the wrong indentation level. I assume this is because we allow spread blocks to be empty, but perhaps we could validate this better.

We should improve the validation behavior of wadm so that it is a little more strict in the places that it accepts "extra" data. This could be handled by improving the [json schema](https://github.com/wasmCloud/wadm/blob/main/oam/oam.schema.json) which is probably the better way since this validation is used in other clients.

**Comment by lachieh** [comment]
Probably still valid

**Comment by lachieh** [comment]
@brooksmtownsend @vados-cosmonic would you say that #274 closed this?

**Comment by lachieh** [comment]
@vados-cosmonic Is the validation logic in its own crate? I'd like to be able to make use of it in a wasm module that takes a string and returns validation errors/success.

**Comment by vados-cosmonic** [comment]
Hey @lachieh yeah -- so `wadm` got refactored into a bunch of crates, and it's in `wadm-types`:

https://crates.io/crates/wadm-types

In particular: https://docs.rs/wadm-types/0.1.0/wadm_types/validation/index.html

Should be easy to use now!

**Comment by lachieh** [comment]
Ok, awesome. Thanks @vados-cosmonic!
