### ISSUE TITLE
[BUG] Manifests do not support labels

### ISSUE THREAD

**Issue by protochron** [wasmCloud/wadm#249]
It looks like we never got around to supporting labels in the OAM manifest spec for Wadm. Just like Kubernetes, the metadata section of a manifest should support arbitrary key/value pairs. See https://github.com/oam-dev/spec/blob/e0991c5d0e666333ebbfa19f3490320bf671d8c0/metadata.md for what the spec calls for.

We may want to also enforce naming requirements for both [labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set) and [annotations](https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/#syntax-and-character-set) while we're at it.

**Comment by joonas** [comment]
To make the case more concrete, in order for the [wasmcloud-operator](https://github.com/wasmcloud/wasmcloud-operator) to more fully interoperate with tools like [Helm](https://helm.sh/docs/chart_best_practices/labels/#standard-labels) or [ArgoCD](https://argo-cd.readthedocs.io/en/stable/user-guide/resource_tracking/) that have defaults built-in for using labels, we really do need the ability to persist labels as part of the manifest.

**Comment by brooksmtownsend** [comment]
Oh does this fail the validation check when you add in a label @protochron ? This is a fairly easy add. What kinds of naming requirements would you like to enforce
