### ISSUE TITLE
[FEATURE] add `wadm.api.{lattice}.status`

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wadm#282]
It'd be nice to be able to get some information about wadm itself across the API. Specifically, the version would be good so that consumers can adjust behavior based on differences between versions.

Sample response:

```jsonc
{
  "wadm_version": "0.0.0"
}
 ```

**Comment by brooksmtownsend** [comment]
Bumping for now, @lachieh would you mind dropping some very minimal information that you'd expect from this endpoint? It would be great to add just a few things and mark it good-first-issue 😄 

What I could think of is mostly:
1. Version of wadm
2. Lattices observed (number or list, list of names is more useful but in the thousands it may overflow the NATS message size)
3. Outstanding commands/events?

**Comment by lachieh** [comment]
Yeah I think those are all valid. My primary use case was the parsing of responses based on the wadm version, but I think those are also great additions. Is there a way to summarize wadm's health? All applications healthy, some pending, errors, etc? That could also be useful here, but not fully necessary. Count is probably fine on the lattices, and outstanding events/commands might be useful as a boolean or a count also.

**Comment by lachieh** [comment]
I updated the description with a sample response. I think it's probably fine to leave this as just the version for an initial implementation and have the additional fields be subsequent features. If you'd like to add more to the response you should have edit access 👍

**Comment by lachieh** [comment]
still valid
