### ISSUE TITLE
[FEAT] Emit application events on wadm topic

### ISSUE THREAD

**Issue by lachieh** [wasmCloud/wadm#285]
It would be good to have some more events to be able to subscribe to for outside systems to understand the state of an application. These are a few events that I know I'd be interested in using but this shouldn't be considered exhaustive.
- Application status change (+ new status message)
- Attempting change (scaling, deploying link, putting config)
- Change successful/failure
- App manifest deployed/undeployed
- Health check (?) passed/failed/constant

**Comment by ahmedtadde** [comment]
after scanning some code, here's what I am thinking:
- have an `else` block [here](https://github.com/ahmedtadde/wadm/blob/b5c471ea2a910a459d96c99414bb2cb1ec6b40bb/crates/wadm/src/scaler/manager.rs#L525-L526) where we dispatch statuses
```rust
                                            if let Err(e) = self
                                                .status_publisher
                                                .publish_status(format!("{}.{}", &name, &parsed_event), Status::new(
                                                    StatusInfo::appropriate_variant_based_on_parsed_event_type(format!({&parsed_event}))
                                                    vector_of_all_scalers_statuses
                                                ))
                                                .await
                                            {
                                                warn!(error = ?e, "Failed to publish application status");
                                            }
```

somethings I have doubts on
- the current status stream is defined/templated as `wadm.status.{lattice_id}.{manifest}`, so I am not sure if that means the proposed app status topic  `wadm.status.{lattice_id}.{manifest}.{parsed_event.raw_type()}` will work or we need to update the definition of the status stream
- in terms of payload for these statuses, are the manifest/application's scaler statuses what we want to send to the listeners; something else entirely? more additional info from the event's inner data/payload?

**Comment by brooksmtownsend** [comment]
> the current status stream is defined/templated as wadm.status.{lattice_id}.{manifest}, so I am not sure if that means the proposed app status topic wadm.status.{lattice_id}.{manifest}.{parsed_event.raw_type()} will work or we need to update the definition of the status stream

I think here we should be able to publish to the topic just fine, but we won't actually be able to persist that status in the status stream. For a first PR we could add these new events which would be available for subscribing, but we'd have to publish the old status events on the old topic still. Using a new topic that's not technically in a stream would be easy, but if we wanted to persist them in a stream we'd have to come up with a good way to limit the number of events we keep for a particular lattice/application

> in terms of payload for these statuses

The payloads should be per-event IMO, the overall application status could still include all of the scaler statuses and the individual events could include smaller sets of information.

What I would see as useful
- App deployed/undeployed, which can mention the version and the application name
- Host reaped, e.g. did not receive a heartbeat 2x and we remove it from state
- @protochron anything else that would be really helpful to know from the operator side?

🔮 As a future change, I'm thinking that this could be a useful status extension:
- Backing off, as implemented in https://github.com/wasmCloud/wadm/pull/379 I was using the notify stream but I think we could use status and react to that change instead, removing the notify stream entirely.
