### ISSUE TITLE
Can't deploy application or retrieve existing applications in WasmCloud

### ISSUE THREAD

**Issue by hasinthajanaka** [wasmCloud/wadm#294]
I am trying to deploy a new application in the wasmcloud using the following command

`wash app deploy wadm.yaml`

It gives the following error,

`Error making model request: no responders: no responders`

The same error appears when I try to list down the existing application.

```
wash app list
Error making model request: no responders: no responders
```
What can be the reason for this

**Comment by brooksmtownsend** [comment]
Hey @hasinthajanaka this looks a lot like https://github.com/wasmCloud/wasmCloud/issues/2204 where @thomastaylor312 answered, I don't mind where we track this issue but once you give it a try let's either continue in #2204 or here 🙂

**Comment by brooksmtownsend** [comment]
Closing in favor of #2204
