### ISSUE TITLE
Failed to update package pc from repo hexpm

### ISSUE THREAD

**Issue by YongBig** [wasmCloud/wadm#31]
Can anybody help me?

I try local compile, and run WADM ，i just got in touch with elixir , I don't know how to solve this problem？

### shell
```bash
-> % mix do  compile         

=NOTICE REPORT==== 24-Aug-2022::18:49:31.264459 ===
TLS client: In state certify at ssl_handshake.erl:2100 generated CLIENT ALERT: Fatal - Handshake Failure
 - {bad_cert,hostname_check_failed}
===> Failed to update package pc from repo hexpm
===> Errors loading plugin pc. Run rebar3 with DEBUG=1 set to see errors.
=NOTICE REPORT==== 24-Aug-2022::18:49:31.327068 ===
TLS client: In state certify at ssl_handshake.erl:2100 generated CLIENT ALERT: Fatal - Handshake Failure
 - {bad_cert,hostname_check_failed}
===> Failed to update package pc from repo hexpm
===> Errors loading plugin pc. Run rebar3 with DEBUG=1 set to see errors.
===> Unable to run pre hooks for 'compile', command 'compile' in namespace 'pc' not found.
** (Mix) Could not compile dependency :snappyer, "/Users/duyong/.mix/rebar3 bare compile --paths /Users/duyong/Desktop/workspace/wadm/wadm/_build/dev/lib/*/ebin" command failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile snappyer", update it with "mix deps.update snappyer" or clean it with "mix deps.clean snappyer"

```

- os : macos
- Elixir: 1.13.4_1
- Erlang: 25.0.4
- rebar 3.15.2 on Erlang/OTP 25 Erts 13.0.4

**Comment by brooksmtownsend** [comment]
Hey @YongBig , have you run "mix deps.get" before compiling?

I've been using OTP 24 for a while and haven't upgraded to OTP 25, but I'll give that a try today once I'm at my computer.

**Comment by brooksmtownsend** [comment]
@YongBig I think this may be due to your need to run `mix deps.get` but we also shouldn't be using snappyer anymore, I opened up #32 to remove that dependency

**Comment by YongBig** [comment]
Hey @brooksmtownsend  , I already run “mix deps.get ” , the error message report when  run "mix do  compile" ,   
Thank you for your help @brooksmtownsend   , i try to pull #32 , Re execute  "mix do deps.get, compile".
> @YongBig I think this may be due to your need to run `mix deps.get` but we also shouldn't be using snappyer anymore, I opened up #32 to remove that dependency

**Comment by YongBig** [comment]
I already pull #32 and run "mix do deps.get, compile" ,  It went well this time
Thanks again @brooksmtownsend
