### ISSUE TITLE
[question] Can this app deploy OAM model applications?

### ISSUE THREAD

**Issue by shikingram** [wasmCloud/wadm#36]
Hi,I found that it publish the json data of the OAM model to nats, who consumed this? It seems that there is currently no introduction in the documentation.😁

**Comment by autodidaddict** [comment]
The application that monitors oam models is wadm, which you can find in the wadm repo

**Comment by thomastaylor312** [comment]
Link for future reference: https://github.com/wasmCloud/wadm
