### ISSUE TITLE
[FEAT] Reflect unhealthy providers in application status

### ISSUE THREAD

**Issue by brooksmtownsend** [wasmCloud/wadm#447]
The Provider spreadscaler + daemonscalers currently handle `provider_start_failed` events to update application status based on application level events. We should extend this handling to also include `health_check_failed` events and `health_check_succeeded` in order to reflect when an application is unhealthy.

We could start this feature using the existing `Failed` status to reflect the issue, but we may want to add an `Unhealthy` status to indicate that the application was scheduled/deployed but with problems.

See https://wasmcloud.com/docs/reference/cloud-event-list#health_check_passed for the event specifications.

**Comment by Vikrantpalle** [comment]
Hey, I would like to have a go at this issue.
