### ISSUE TITLE
Wadm missing log-level configuration

### ISSUE THREAD

**Issue by peter-jerry-ye** [wasmCloud/wadm#450]
It would be great if wadm can have a log level configuration just as wasmcloud host so that debug messages can be printed.

Also, the `values.yaml` in the chart seem to have that configuration at `wadm.config.logLevel`, which is a bit misleading.

**Comment by brooksmtownsend** [comment]
Ah yep here we've used `RUST_LOG` as the log level directive, just hooking into the native Rust support. I think it would be more clear to have a log level flag/env var.
