### ISSUE TITLE
[BUG] wash app delete command returns success for invalid application name

### ISSUE THREAD

**Issue by ffuerste** [wasmCloud/wadm#502]
## Affected project(s)

- [ ] documentation
- [ ] examples
- [ ] wasmCloud host
- [x] wasmCloud CLI (wash)
- [ ] wasmCloud dashboard UI (washboard)
- [ ] capability providers
- [ ] provider bindgen
- [ ] control interface client
- [ ] other / not sure

## Describe the bug

If an incorrect model name is passed without a version to the `wash app del <app_name>` command, it still outputs a success message ("Deleted application: <app_name>") even though this app does not exist.

## Steps to reproduce

- list all applications with `wash app list`
- try to delete an app using an invalid name without specifying a version
- check the apps again with `wash app list` to confirm no changes have occurred

Example:

```sh
$ wash app list
  Name                                  Deployed Version                      Status
  rust-hello-world                      01JE99W346KMJR9XG33FE7QBYM            Deployed
    └ HTTP hello world demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)
```

```sh
$ wash app del test
Deleted application: test
```

```sh
$ wash app list
  Name                                  Deployed Version                      Status
  rust-hello-world                      01JE99W346KMJR9XG33FE7QBYM            Deployed
    └ HTTP hello world demo in Rust, using the WebAssembly Component Model and WebAssembly Interfaces Types (WIT)
```

## Expected behavior

The `wash app del` command should return a meaningful message for invalid app names instead of printing a success message. The output should be the same as for invalid versions:

```sh
$ wash app del test 1.0.0
Already deleted application: test
```

## Environment

- OS: MacOS
- Shell: zsh
- wasmcloud Versions:
  ```sh
  $ wash -V
  wash          v0.37.0
  ├ nats-server v2.10.20
  ├ wadm        v0.18.0
  └ wasmcloud   v1.4.2
  ```

## Root Cause

`wadm` only checks wether the application actually exists if a version has been specified (see [here](https://github.com/wasmCloud/wadm/blob/main/crates/wadm/src/server/handlers.rs#L417)). If no version was specified, `wadm` simply deletes the application manifest (see [here](https://github.com/wasmCloud/wadm/blob/main/crates/wadm/src/server/handlers.rs#L493)) without covering the `DeleteResult::Noop` case.

## Proposal

Checking first if for the specified application a manifest exists and start a deletion attempt only in case it does. Otherwise return early with `DeleteResult::Noop`.

If you agree with my proposal, I would be happy to create a PR for it.

**Comment by brooksmtownsend** [comment]
@ffuerste I agree here! I think we should still mark the operation as successful for idempotency, but we should indicate that the application was "already deleted" as you said. Please feel free to open a PR anytime
