### ISSUE TITLE
Trigger reconciliation when a node is reaped

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wadm#80]
We need to make sure all scalers try to reconcile if a node "ages out" from the store. I think there are two different ways to do this: 

1. Create a new `NodeReaped` event that gets emitted to `wadm.evt.{lattice-id}`
2. Create a new `ForceReconcile` event that gets emitted to `wadm.evt.{lattice-id}`

I'm more in favor of option 2 because it gives us more flexibility. It would also allow a user to force a reconciliation pass if they ever wanted to (by emitting the correct event to the right topic)

**Comment by thomastaylor312** [comment]
After further investigation, this is more of a nice to have. All the reconcilers will run when they get a host heartbeat that pertains to them (which should always be at least 1 otherwise it couldn't reconcile anyway) so it will only be a max of 30-ish seconds before things reconcile in case of a reaping

**Comment by brooksmtownsend** [comment]
not stale
