### ISSUE TITLE
Remove mirror stream on update to NATS 2.10

### ISSUE THREAD

**Issue by thomastaylor312** [wasmCloud/wadm#81]
In #79 we added some things around a mirror stream for combining streams. In NATS 2.10, we will be able to have multiple filter subjects and won't need it any more. So once we update, we should remove the need for a mirror stream

**Comment by connorsmith256** [comment]
@thomastaylor312 was this okay to close as stale?

**Comment by thomastaylor312** [comment]
Nope. Let me label

**Comment by brooksmtownsend** [comment]
Done in https://github.com/wasmCloud/wadm/pull/310
